### ISSUE TITLE
You've Activated Your TS Membership - Now What? - Blog post

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#731] opened 2021-03-29 17:02 UTC
## 📋   Anything to add?
Short piece, just talking about some of the next steps. How to earn CSTK, particpate in hatches, CV pilots, etc

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment] 2021-03-29 17:44
@krisjpi need to mention that CSTK holdings may affect how much you can contribute in TEC and other hatches

**Comment by tamarandom** [comment] 2021-05-24 17:33
Dupe of #732?

**Comment by GriffGreen** [comment] 2021-08-02 17:07
Justice and Kris have been discussing this... will prob go into the CSTK piece of be its own piece

**Comment by krisjpi** [comment] 2021-08-16 16:28
Started the piece - not quite at a shareable draft yet.

**Comment by tamarandom** [comment] 2022-05-10 08:10
This is quite an old issue and I think this is rolled into the plans @MaxSemenchuk has going for Trusted Seed already but @mafer-cordovas @YineisyM @iviangita, putting on your radar. Should this be closed?

**Comment by tamarandom** [comment] 2022-05-17 13:02
Thumbs up from @MaxSemenchuk to close.

**Closed by tamarandom** 2022-05-17 13:02 UTC
Labels: 🌱 Trusted Seed / CSA 🌱
