### ISSUE TITLE
Praise Content for givepraise.xyz

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1448] opened 2022-07-01 09:07 UTC
## 📋   Anything to add?

In progress

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment] 2022-07-04 13:27
Dupe of #1422

**Closed as completed by tamarandom** 2022-07-04 13:27 UTC
Labels: Praise Deployments
