### ISSUE TITLE
Retro action: Work out the Praise goals and "business plan"

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1368] opened 2022-05-09 13:09 UTC
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by kristoferlund** [comment] 2022-05-23 13:08
Duplicate of #1320, closing

**Closed as completed by kristoferlund** 2022-05-23 13:08 UTC
Labels: 🏃 Next sprint? 🏃
