### ISSUE TITLE
Update Trusted Seed Membership List

### ISSUE THREAD

**Issue by kosmostasis** [commons-stack/iteration0#939] opened 2021-08-04 10:45 UTC
## 📋   Anything to add?
Updating the list with the latest active members, member count and total CSTK in supply.

This list: https://member.commonsstack.foundation/members

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment] 2021-10-11 17:59
Dan will pass to Maria & Yineisy

**Comment by mafer-labs** [comment] 2021-12-28 16:21
@kristoferlund we found a problem while updating the JSON. I will reach out for support.

The issue is that the JSON is not applying changes and it deletes the modification history.

**Comment by tamarandom** [comment] 2022-03-28 13:04
Update: This is on hold because the dashboard will have the membership list when it launches and to fix it will take dev time away from higher priority projects. 

Closing.

**Closed as completed by tamarandom** 2022-03-28 13:04 UTC
