### ISSUE TITLE
TEC Website

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#218] opened 2020-11-02 17:44 UTC
## 📋   Anything to add?

CC from TEC https://github.com/TECommons/Coordination/issues/1

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment] 2020-11-24 21:04
Duplicate of #1 in  https://github.com/TECommons/Coordination/issues/1

**Closed by tamarandom** 2020-11-24 21:04 UTC
Labels: Communication, Community, November
