### ISSUE TITLE
Metaverde - Join the Swiss Association, make issues, apply for scholarship

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#506] opened 2021-01-27 17:11 UTC
- [ ] Get 450 DAI and >0.01 ETH in your CSTK address
- [ ] Follow thru on the App (wait till Tuesday to start) https://develop--tech-dapp.netlify.app/contribute
- [ ] Make at least 1 issue here! https://github.com/commons-stack/tech-dapp/issues/new
- [ ] Apply for the scholarship if you would like (Griff will work on this, in this sprint, will be ready by the weekend)

**Comment by tamarandom** [comment] 2021-02-10 15:08
Dupe of https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/424 in the TEC repository. ;)

**Closed by tamarandom** 2021-02-10 15:08 UTC
Labels: For Contributors

**Comment by metaverde** [comment] 2021-02-10 16:01
The epic is #408.
;-)

**Comment by tamarandom** [comment] 2021-02-10 16:08
Hey @metaverde ! That's right. You have an issue assigned in that Epic. 

The TEC and CS have two different repositories. We had an issue open in both for you. I closed the one in CS and am leaving the one open in TEC. That's all!
